export const CAMINERO_TENANT_ID = 'b39506c3-27dc-467d-830b-096731b83113';

const now = new Date();
const hoursAgo = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const mockGpsDevices = [
  {
    id: 'gps-001',
    empresa_id: CAMINERO_TENANT_ID,
    imei: '868204059100001',
    sim_number: '829-555-1101',
    modelo: 'Teltonika FMC920',
    proveedor: 'MockGps',
    estado: 'instalado',
    installed_at: daysAgo(92),
    cliente_id: 'cli-001',
    cliente: 'Ramon Antonio Mejia',
    telefono: '809-222-1040',
    vehiculo_id: 'veh-001',
    moto: 'CG 200 Rojo 2024',
    placa: 'K187201',
    chasis: 'LC6PAGCJ0R100001',
    contrato_id: 'fin-001',
    balance_pendiente: 74500,
    cuota_vencida: 0,
    dias_atraso: 0,
    geofence: 'Santo Domingo Este',
  },
  {
    id: 'gps-002',
    empresa_id: CAMINERO_TENANT_ID,
    imei: '868204059100002',
    sim_number: '829-555-1102',
    modelo: 'Concox GT06N',
    proveedor: 'MockGps',
    estado: 'instalado',
    installed_at: daysAgo(61),
    cliente_id: 'cli-002',
    cliente: 'Yudelka Mercedes Pena',
    telefono: '849-333-2091',
    vehiculo_id: 'veh-002',
    moto: 'Loncin LX200 Negro',
    placa: 'K220884',
    chasis: 'LX6PCKL10R100002',
    contrato_id: 'fin-002',
    balance_pendiente: 92000,
    cuota_vencida: 3900,
    dias_atraso: 4,
    geofence: 'Higuey Centro',
  },
  {
    id: 'gps-003',
    empresa_id: CAMINERO_TENANT_ID,
    imei: '868204059100003',
    sim_number: '829-555-1103',
    modelo: 'Teltonika FMB125',
    proveedor: 'MockGps',
    estado: 'instalado',
    installed_at: daysAgo(145),
    cliente_id: 'cli-003',
    cliente: 'Jose Miguel Caminero',
    telefono: '809-444-3090',
    vehiculo_id: 'veh-003',
    moto: 'Yamaha YBR 125 Azul',
    placa: 'K998201',
    chasis: 'YBR125R100003',
    contrato_id: 'fin-003',
    balance_pendiente: 116500,
    cuota_vencida: 7800,
    dias_atraso: 11,
    geofence: 'La Romana',
  },
  {
    id: 'gps-004',
    empresa_id: CAMINERO_TENANT_ID,
    imei: '868204059100004',
    sim_number: '829-555-1104',
    modelo: 'Concox JM-VL03',
    proveedor: 'MockGps',
    estado: 'instalado',
    installed_at: daysAgo(210),
    cliente_id: 'cli-004',
    cliente: 'Ana Iris Cedano',
    telefono: '829-515-7741',
    vehiculo_id: 'veh-004',
    moto: 'Tauro CG250 Blanco',
    placa: 'K551029',
    chasis: 'TAUCG250R100004',
    contrato_id: 'fin-004',
    balance_pendiente: 138900,
    cuota_vencida: 15600,
    dias_atraso: 22,
    geofence: 'San Pedro',
  },
  {
    id: 'gps-005',
    empresa_id: CAMINERO_TENANT_ID,
    imei: '868204059100005',
    sim_number: '829-555-1105',
    modelo: 'Teltonika FMC130',
    proveedor: 'MockGps',
    estado: 'suspendido',
    installed_at: daysAgo(28),
    cliente_id: 'cli-005',
    cliente: 'Carlos Manuel Ortiz',
    telefono: '849-288-9001',
    vehiculo_id: 'veh-005',
    moto: 'Suzuki AX100 Gris',
    placa: 'K772101',
    chasis: 'SUZAX100R100005',
    contrato_id: 'fin-005',
    balance_pendiente: 64300,
    cuota_vencida: 5200,
    dias_atraso: 18,
    geofence: 'Bavaro',
  },
  {
    id: 'gps-006',
    empresa_id: CAMINERO_TENANT_ID,
    imei: '868204059100006',
    sim_number: '829-555-1106',
    modelo: 'Concox GT06N',
    proveedor: 'MockGps',
    estado: 'sin_senal',
    installed_at: daysAgo(70),
    cliente_id: 'cli-006',
    cliente: 'Francisca Altagracia Mota',
    telefono: '809-777-4102',
    vehiculo_id: 'veh-006',
    moto: 'Zontes ZT150 Negro',
    placa: 'K110876',
    chasis: 'ZONZT150R100006',
    contrato_id: 'fin-006',
    balance_pendiente: 81000,
    cuota_vencida: 2500,
    dias_atraso: 2,
    geofence: 'Hato Mayor',
  },
  {
    id: 'gps-007',
    empresa_id: CAMINERO_TENANT_ID,
    imei: '868204059100007',
    sim_number: '829-555-1107',
    modelo: 'Teltonika FMC920',
    proveedor: 'MockGps',
    estado: 'instalado',
    installed_at: daysAgo(35),
    cliente_id: 'cli-007',
    cliente: 'Miguel Angel Reyes',
    telefono: '829-644-0028',
    vehiculo_id: 'veh-007',
    moto: 'Honda Dio Roja',
    placa: 'K330118',
    chasis: 'HDIODLX100007',
    contrato_id: 'fin-007',
    balance_pendiente: 42000,
    cuota_vencida: 0,
    dias_atraso: 0,
    geofence: 'Santiago',
  },
  {
    id: 'gps-008',
    empresa_id: CAMINERO_TENANT_ID,
    imei: '868204059100008',
    sim_number: '829-555-1108',
    modelo: 'Teltonika FMB920',
    proveedor: 'MockGps',
    estado: 'en_inventario',
    installed_at: null,
    cliente_id: null,
    cliente: 'Sin asignar',
    telefono: 'N/A',
    vehiculo_id: null,
    moto: 'Sin asociar',
    placa: 'N/A',
    chasis: 'N/A',
    contrato_id: null,
    balance_pendiente: 0,
    cuota_vencida: 0,
    dias_atraso: 0,
    geofence: 'Inventario',
  },
  {
    id: 'gps-009',
    empresa_id: CAMINERO_TENANT_ID,
    imei: '868204059100009',
    sim_number: '829-555-1109',
    modelo: 'Concox JM-VL03',
    proveedor: 'MockGps',
    estado: 'instalado',
    installed_at: daysAgo(120),
    cliente_id: 'cli-009',
    cliente: 'Leidy Carolina Alcantara',
    telefono: '849-600-4002',
    vehiculo_id: 'veh-009',
    moto: 'Bajaj Boxer 150 Verde',
    placa: 'K290011',
    chasis: 'BAJBOX150R100009',
    contrato_id: 'fin-009',
    balance_pendiente: 103200,
    cuota_vencida: 10400,
    dias_atraso: 16,
    geofence: 'Fuera de zona',
  },
  {
    id: 'gps-010',
    empresa_id: CAMINERO_TENANT_ID,
    imei: '868204059100010',
    sim_number: '829-555-1110',
    modelo: 'Teltonika FMC130',
    proveedor: 'MockGps',
    estado: 'instalado',
    installed_at: daysAgo(48),
    cliente_id: 'cli-010',
    cliente: 'Kelvin Joel Batista',
    telefono: '809-510-7610',
    vehiculo_id: 'veh-010',
    moto: 'Gato CG200 Negro',
    placa: 'K887001',
    chasis: 'GATCG200R100010',
    contrato_id: 'fin-010',
    balance_pendiente: 69700,
    cuota_vencida: 6900,
    dias_atraso: 9,
    geofence: 'Punta Cana',
  },
];

export const mockGpsPositions = [
  { id: 'pos-001', gps_device_id: 'gps-001', lat: 18.4861, lng: -69.8412, speed: 22, heading: 80, ignition: true, battery_level: 84, gsm_signal: 76, event_type: 'position', recorded_at: hoursAgo(0.25) },
  { id: 'pos-002', gps_device_id: 'gps-002', lat: 18.6169, lng: -68.7074, speed: 0, heading: 0, ignition: false, battery_level: 61, gsm_signal: 64, event_type: 'parked', recorded_at: hoursAgo(0.6) },
  { id: 'pos-003', gps_device_id: 'gps-003', lat: 18.4273, lng: -68.9728, speed: 34, heading: 140, ignition: true, battery_level: 44, gsm_signal: 52, event_type: 'position', recorded_at: hoursAgo(1.1) },
  { id: 'pos-004', gps_device_id: 'gps-004', lat: 18.4539, lng: -69.3042, speed: 12, heading: 40, ignition: true, battery_level: 18, gsm_signal: 45, event_type: 'low_battery', recorded_at: hoursAgo(2.4) },
  { id: 'pos-005', gps_device_id: 'gps-005', lat: 18.7101, lng: -68.4382, speed: 0, heading: 0, ignition: null, battery_level: 12, gsm_signal: 14, event_type: 'disconnect', recorded_at: hoursAgo(5) },
  { id: 'pos-006', gps_device_id: 'gps-006', lat: 18.7614, lng: -69.2575, speed: 0, heading: 0, ignition: false, battery_level: 50, gsm_signal: 0, event_type: 'no_signal', recorded_at: hoursAgo(31) },
  { id: 'pos-007', gps_device_id: 'gps-007', lat: 19.4517, lng: -70.6970, speed: 18, heading: 270, ignition: true, battery_level: 77, gsm_signal: 81, event_type: 'position', recorded_at: hoursAgo(0.4) },
  { id: 'pos-008', gps_device_id: 'gps-008', lat: 18.6150, lng: -68.7080, speed: 0, heading: 0, ignition: false, battery_level: 100, gsm_signal: 90, event_type: 'inventory', recorded_at: hoursAgo(12) },
  { id: 'pos-009', gps_device_id: 'gps-009', lat: 18.9712, lng: -69.0398, speed: 48, heading: 15, ignition: true, battery_level: 36, gsm_signal: 58, event_type: 'outside_geofence', recorded_at: hoursAgo(0.9) },
  { id: 'pos-010', gps_device_id: 'gps-010', lat: 18.5660, lng: -68.3683, speed: 6, heading: 205, ignition: true, battery_level: 24, gsm_signal: 60, event_type: 'position', recorded_at: hoursAgo(3) },
];

export const mockGpsHistory = mockGpsPositions.flatMap((pos, index) =>
  Array.from({ length: 8 }).map((_, step) => ({
    ...pos,
    id: `${pos.id}-h${step}`,
    lat: Number((pos.lat + (step - 4) * 0.006 + index * 0.0007).toFixed(6)),
    lng: Number((pos.lng + (step - 4) * 0.007 - index * 0.0005).toFixed(6)),
    speed: Math.max(0, Number(pos.speed || 0) + ((step % 3) - 1) * 5),
    recorded_at: hoursAgo(step * 2 + index / 4),
  }))
);

export const mockGeofences = [
  { id: 'geo-001', empresa_id: CAMINERO_TENANT_ID, nombre: 'Higuey Centro', tipo: 'circulo', center_lat: 18.615, center_lng: -68.708, radius_meters: 7000, activa: true },
  { id: 'geo-002', empresa_id: CAMINERO_TENANT_ID, nombre: 'Santo Domingo Este', tipo: 'circulo', center_lat: 18.486, center_lng: -69.841, radius_meters: 9000, activa: true },
  { id: 'geo-003', empresa_id: CAMINERO_TENANT_ID, nombre: 'Bavaro', tipo: 'circulo', center_lat: 18.71, center_lng: -68.438, radius_meters: 10000, activa: true },
];

export const buildMockAlerts = () => {
  const latestByDevice = new Map(mockGpsPositions.map(p => [p.gps_device_id, p]));
  const alerts: any[] = [];

  mockGpsDevices.forEach(device => {
    const pos = latestByDevice.get(device.id);
    if (device.dias_atraso > 0) {
      alerts.push({
        id: `fin-${device.id}`,
        empresa_id: CAMINERO_TENANT_ID,
        gps_device_id: device.id,
        cliente_id: device.cliente_id,
        vehiculo_id: device.vehiculo_id,
        cliente: device.cliente,
        moto: device.moto,
        tipo: 'atraso',
        nivel: device.dias_atraso > 15 ? 'critico' : device.dias_atraso > 7 ? 'alto' : 'medio',
        titulo: `${device.dias_atraso} dia(s) de atraso`,
        descripcion: `Cuota vencida por RD$${Number(device.cuota_vencida).toLocaleString('es-DO')}.`,
        estado: 'pendiente',
        accion_recomendada: device.dias_atraso > 15 ? 'Escalar a recuperacion y validar ubicacion.' : 'Contactar cliente y confirmar promesa de pago.',
        created_at: hoursAgo(device.dias_atraso > 15 ? 1 : 8),
      });
    }
    if (!pos) return;
    const last = new Date(pos.recorded_at).getTime();
    if ((Date.now() - last) / 3600000 > 24) {
      alerts.push({
        id: `signal-${device.id}`,
        empresa_id: CAMINERO_TENANT_ID,
        gps_device_id: device.id,
        cliente_id: device.cliente_id,
        vehiculo_id: device.vehiculo_id,
        cliente: device.cliente,
        moto: device.moto,
        tipo: 'sin_senal',
        nivel: 'alto',
        titulo: 'GPS sin senal por mas de 24h',
        descripcion: `Ultimo reporte: ${new Date(pos.recorded_at).toLocaleString('es-DO')}.`,
        estado: 'pendiente',
        accion_recomendada: 'Verificar cobertura, SIM o posible desconexion.',
        created_at: hoursAgo(2),
      });
    }
    if (Number(pos.battery_level || 0) < 20) {
      alerts.push({
        id: `bat-${device.id}`,
        empresa_id: CAMINERO_TENANT_ID,
        gps_device_id: device.id,
        cliente_id: device.cliente_id,
        vehiculo_id: device.vehiculo_id,
        cliente: device.cliente,
        moto: device.moto,
        tipo: 'bateria_baja',
        nivel: 'alto',
        titulo: 'Bateria baja del GPS',
        descripcion: `Nivel actual ${pos.battery_level}%.`,
        estado: 'pendiente',
        accion_recomendada: 'Coordinar revision tecnica del equipo.',
        created_at: hoursAgo(3),
      });
    }
    if (pos.event_type === 'disconnect' || pos.ignition === null) {
      alerts.push({
        id: `disc-${device.id}`,
        empresa_id: CAMINERO_TENANT_ID,
        gps_device_id: device.id,
        cliente_id: device.cliente_id,
        vehiculo_id: device.vehiculo_id,
        cliente: device.cliente,
        moto: device.moto,
        tipo: 'gps_desconectado',
        nivel: 'critico',
        titulo: 'GPS desconectado',
        descripcion: 'El equipo reporto evento de desconexion.',
        estado: 'pendiente',
        accion_recomendada: 'Contactar cliente y activar protocolo tecnico.',
        created_at: hoursAgo(5),
      });
    }
    if (pos.event_type === 'outside_geofence') {
      alerts.push({
        id: `geo-${device.id}`,
        empresa_id: CAMINERO_TENANT_ID,
        gps_device_id: device.id,
        cliente_id: device.cliente_id,
        vehiculo_id: device.vehiculo_id,
        cliente: device.cliente,
        moto: device.moto,
        tipo: 'fuera_geocerca',
        nivel: 'medio',
        titulo: 'Moto fuera de geocerca',
        descripcion: 'La unidad se movio fuera de su zona esperada.',
        estado: 'pendiente',
        accion_recomendada: 'Validar motivo del desplazamiento con el cliente.',
        created_at: hoursAgo(1),
      });
    }
  });

  return alerts.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
};
