// Fix: sequences + ARRAY types for failed tables
const TOKEN = 'sbp_7dd6d35c4dfe60c44628b58b40274becf961eb9d';
const PROD = 'zdvxowpuklbypweyqqki';
const DEV  = 'vvxoxhowupkehycnpwaa';
const API  = 'https://api.supabase.com/v1';
const H    = { 'Authorization': `Bearer ${TOKEN}`, 'Content-Type': 'application/json' };

const q = async (ref, query) => {
  const r = await fetch(`${API}/projects/${ref}/database/query`, { method:'POST', headers:H, body:JSON.stringify({query}) });
  const d = await r.json();
  if (!r.ok) throw new Error(JSON.stringify(d).slice(0,300));
  return d;
};

const run = async (name, query) => {
  try { await q(DEV, query); console.log(`  ✅ ${name}`); return true; }
  catch(e) { console.log(`  ⚠️  ${name}: ${e.message.slice(0,120)}`); return false; }
};

async function main() {
  console.log('🔧 Fase 1: Creando secuencias faltantes...\n');

  // Get all sequences from prod with their proper definitions
  const seqs = await q(PROD, `
    SELECT s.relname AS seqname,
           seq.seqstart AS start_val,
           seq.seqmin AS min_val,
           seq.seqmax AS max_val,
           seq.seqincrement AS inc,
           seq.seqcycle AS is_cycle
    FROM pg_class s
    JOIN pg_sequence seq ON seq.seqrelid = s.oid
    JOIN pg_namespace n ON n.oid = s.relnamespace
    WHERE n.nspname = 'public' AND s.relkind = 'S'
    ORDER BY s.relname
  `);

  for (const s of seqs) {
    await run(`Sequence: ${s.seqname}`,
      `CREATE SEQUENCE IF NOT EXISTS public."${s.seqname}" START ${s.start_val} MINVALUE ${s.min_val} MAXVALUE ${s.max_val} INCREMENT ${s.inc} ${s.is_cycle ? 'CYCLE' : 'NO CYCLE'};`
    );
  }

  console.log('\n🔧 Fase 2: Creando tablas con tipos correctos (usando format_type)...\n');

  // Get proper column definitions using pg_attribute + format_type
  const failedTables = ['compras', 'devoluciones', 'facturas', 'pedidos', 'productos', 'transacciones_unificadas_temp', 'user_module_permissions'];

  for (const tbl of failedTables) {
    const cols = await q(PROD, `
      SELECT
        a.attname AS name,
        format_type(a.atttypid, a.atttypmod) AS type,
        pg_get_expr(d.adbin, d.adrelid) AS default_val,
        a.attnotnull AS not_null,
        a.attidentity AS identity
      FROM pg_attribute a
      JOIN pg_class c ON c.oid = a.attrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
      WHERE n.nspname = 'public' AND c.relname = '${tbl}'
        AND a.attnum > 0 AND NOT a.attisdropped
      ORDER BY a.attnum
    `);

    const colDefs = cols.map(c => {
      let def = `  "${c.name}" ${c.type}`;
      if (c.identity === 'a') def += ' GENERATED ALWAYS AS IDENTITY';
      else if (c.identity === 'd') def += ' GENERATED BY DEFAULT AS IDENTITY';
      else if (c.default_val) def += ` DEFAULT ${c.default_val}`;
      if (c.not_null) def += ' NOT NULL';
      return def;
    });

    await run(`Table: ${tbl}`,
      `CREATE TABLE IF NOT EXISTS public."${tbl}" (\n${colDefs.join(',\n')}\n);`
    );
  }

  console.log('\n🔧 Fase 3: PKs, FKs, Unique para tablas corregidas...\n');

  // PKs for failed tables
  const pks = await q(PROD, `
    SELECT tc.table_name, tc.constraint_name,
      string_agg('"' || kcu.column_name || '"', ', ' ORDER BY kcu.ordinal_position) AS cols
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
    WHERE tc.constraint_type = 'PRIMARY KEY' AND tc.table_schema = 'public'
      AND tc.table_name = ANY(ARRAY['compras','devoluciones','facturas','pedidos','productos','transacciones_unificadas_temp','user_module_permissions'])
    GROUP BY tc.table_name, tc.constraint_name ORDER BY tc.table_name
  `);

  for (const pk of pks) {
    await run(`PK: ${pk.table_name}`,
      `ALTER TABLE public."${pk.table_name}" ADD CONSTRAINT "${pk.constraint_name}" PRIMARY KEY (${pk.cols});`
    );
  }

  // All FKs (retry all since they depend on previously failed tables)
  const fks = await q(PROD, `
    SELECT tc.table_name, tc.constraint_name,
      string_agg('"' || kcu.column_name || '"', ', ' ORDER BY kcu.ordinal_position) AS cols,
      ccu.table_name AS ref_table,
      string_agg('"' || ccu.column_name || '"', ', ' ORDER BY kcu.ordinal_position) AS ref_cols,
      rc.delete_rule, rc.update_rule
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
    JOIN information_schema.referential_constraints rc ON tc.constraint_name = rc.constraint_name
    JOIN information_schema.constraint_column_usage ccu ON rc.unique_constraint_name = ccu.constraint_name
    WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = 'public'
    GROUP BY tc.table_name, tc.constraint_name, ccu.table_name, rc.delete_rule, rc.update_rule
    ORDER BY tc.table_name
  `);

  for (const fk of fks) {
    await run(`FK: ${fk.constraint_name}`,
      `ALTER TABLE public."${fk.table_name}" ADD CONSTRAINT "${fk.constraint_name}" FOREIGN KEY (${fk.cols}) REFERENCES public."${fk.ref_table}" (${fk.ref_cols}) ON DELETE ${fk.delete_rule} ON UPDATE ${fk.update_rule};`
    );
  }

  // Unique constraints for failed tables
  const uqs = await q(PROD, `
    SELECT tc.table_name, tc.constraint_name,
      string_agg('"' || kcu.column_name || '"', ', ' ORDER BY kcu.ordinal_position) AS cols
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
    WHERE tc.constraint_type = 'UNIQUE' AND tc.table_schema = 'public'
      AND tc.table_name = ANY(ARRAY['compras','devoluciones','facturas','pedidos','productos','transacciones_unificadas_temp','user_module_permissions'])
    GROUP BY tc.table_name, tc.constraint_name ORDER BY tc.table_name
  `);

  for (const u of uqs) {
    await run(`Unique: ${u.constraint_name}`,
      `ALTER TABLE public."${u.table_name}" ADD CONSTRAINT "${u.constraint_name}" UNIQUE (${u.cols});`
    );
  }

  console.log('\n🔧 Fase 4: RLS para tablas corregidas...\n');

  const policies = await q(PROD, `
    SELECT tablename, policyname, permissive, roles, cmd, qual, with_check
    FROM pg_policies WHERE schemaname = 'public'
      AND tablename = ANY(ARRAY['compras','devoluciones','facturas','pedidos','productos','transacciones_unificadas_temp','user_module_permissions'])
    ORDER BY tablename, policyname
  `);

  const rlsTables = [...new Set(policies.map(p => p.tablename))];
  for (const t of rlsTables) {
    await run(`RLS enable: ${t}`, `ALTER TABLE public."${t}" ENABLE ROW LEVEL SECURITY;`);
  }
  for (const p of policies) {
    let def = `CREATE POLICY "${p.policyname}" ON public."${p.tablename}" AS ${p.permissive} FOR ${p.cmd}`;
    if (p.roles && p.roles !== '{}') def += ` TO ${p.roles.replace(/[{}]/g,'')}`;
    if (p.qual) def += ` USING (${p.qual})`;
    if (p.with_check) def += ` WITH CHECK (${p.with_check})`;
    await run(`Policy: ${p.policyname} on ${p.tablename}`, `${def};`);
  }

  console.log('\n🎉 Corrección completada.');

  // Verify
  const devTables = await q(DEV, `SELECT count(*) as n FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'`);
  const prodTables = await q(PROD, `SELECT count(*) as n FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'`);
  console.log(`\n📊 Tablas — PROD: ${prodTables[0].n} | DEV: ${devTables[0].n}`);
}

main().catch(e => { console.error('❌', e.message); process.exit(1); });
